language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560
- BOARD=due

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
